### PR TITLE
First phase of C++ conversion trial

### PR DESCRIPTION
**Pull request by dcwhite**
For #21; doesn't quite close it yet, will wait for more work from @akilnarayan on families.py. See https://sciinstitute.slack.com/archives/CSZMPU448/p1588867871005800

### CODE REVIEW

**Comment by akilnarayan** [comment]
I can't get this to compile. Running cmake results in:
```
-- Check for working CXX compiler: /opt/local/bin/g++-mp-9 - broken
CMake Error at /Applications/CMake.app/Contents/share/cmake-3.17/Modules/CMakeTestCXXCompiler.cmake:53 (message):
  The C++ compiler

    "/opt/local/bin/g++-mp-9"

  is not able to compile a simple test program.
.
.
.
g++-mp-9: error: unrecognized command line option '-stdlib=libc++'
```
I think the `-stdlib` option is a clang option?
The g++ compiler that's used is from macports. So I tried to force cmake to use my clang compiler, with something like
```
cmake CMAKE_C_COMPILER=/usr/bin/gcc CMAKE_CXX_COMPILER=/usr/bin/g++ .
```
which produced the same error (still uses the macports compiler). I also tried exporting the`CC` and `CXX` variables as in 
[https://stackoverflow.com/questions/17275348/how-to-specify-new-gcc-path-for-cmake](https://stackoverflow.com/questions/17275348/how-to-specify-new-gcc-path-for-cmake)

Still no luck. Any tips?

**Comment by dcwhite** [comment]
I'll investigate today!

**Comment by dcwhite** [comment]
I got brew gcc to build it on the github VM, like so: 
```
env:
        CC: /usr/local/Cellar/gcc/9.3.0_1/bin/gcc-9
        CXX: /usr/local/Cellar/gcc/9.3.0_1/bin/g++-9
      run: cmake .. -DCMAKE_C_COMPILER=$CC -DCMAKE_CXX_COMPILER=$CXX
```

Can you try setting the compilers to the non-symlinked macports location? And use "-D" in the command line.

**Comment by akilnarayan** [comment]
Ah, it was the `-D` that I messed up. Recognizes clang fine now. But I need to install Eigen. Getting on that.

**Comment by akilnarayan** [comment]
I'd say that the next ones to convert at are: 
- `jacobi_idist_driver` in `families.py`
- `idistinv_driver` in `opoly1d.py`

**Comment by jessdtate** [comment]
I'm getting a compiler error.
/Users/jess/software/UncertainSCI/cpptests/src/Math/types.h:17:22: error: no template named 'variant' in namespace 'std'
  using XType = std::variant<int, double, Vector1D>;

**Comment by dcwhite** [comment]
What OS/compiler? It’ll work on 10.14 for sure.

**Comment by dcwhite** [comment]
You might need to update Xcode

**Comment by dcwhite** [comment]
Looking at those next functions, they will be another level harder than the first wave of conversions. Are they easy to unit test in isolation, to provide a quicker conversion pathway, or should I just examine where they are used and try to build a test using that?

**Comment by akilnarayan** [comment]
For `jacobi_idist_driver`, we have a unit test for a slightly higher-level function, `JacobiPolynomials.idist` in `families.py`. Would you be able to use that? The unit test is `test_idist_legendre` in `tests/jacobipolys.py`. 

If you'd rather test `jacobi_idist_driver` in isolation, let me know and I'll make a unit test for it.

For the second function I mentioned above, `idistinv_driver`, that can be done after we figure this one out.
